#' Example Time Series Data
#'
#' @description An example of time series data (n=200) which can be used with backtesting functions
#'
#' @usage ex_ts
#'
#' @source Generated by arima.sim(list(order = c(2,0,2), ar = c(0.7,-0.4),ma=c(0.7,-0.4)), n = 200)
#' @format A time series start from 1950
#'
#' @examples plot(ex_ts)
#' @export

"ex_ts"
